"use client";

import {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Barbell,
  Briefcase,
  ChartLineUp,
  Buildings,
  CaretDoubleDown,
  Check,
  Code,
  Copy,
  Database,
  DownloadSimple,
  Envelope,
  FileArrowDown,
  Flag,
  FlowArrow,
  GraduationCap,
  Handshake,
  Kanban,
  Keyboard,
  Lightning,
  LinkedinLogo,
  ListBullets,
  MapPin,
  Medal,
  Mountains,
  MouseScroll,
  Notebook,
  Pause,
  Play,
  Robot,
  Rocket,
  Snowflake,
  SpeakerHigh,
  SpeakerSlash,
  Sparkle,
  Stack,
  Target,
  Translate,
  Trophy,
  UsersThree,
  Wrench,
  X,
  type Icon as PhosphorIcon,
} from "@phosphor-icons/react";

const ICONS = {
  "arrow-counter-clockwise": ArrowCounterClockwise,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  barbell: Barbell,
  briefcase: Briefcase,
  "chart-line-up": ChartLineUp,
  buildings: Buildings,
  "caret-double-down": CaretDoubleDown,
  check: Check,
  code: Code,
  copy: Copy,
  database: Database,
  download: DownloadSimple,
  envelope: Envelope,
  "file-arrow-down": FileArrowDown,
  flag: Flag,
  "flow-arrow": FlowArrow,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  kanban: Kanban,
  keyboard: Keyboard,
  lightning: Lightning,
  linkedin: LinkedinLogo,
  list: ListBullets,
  "map-pin": MapPin,
  medal: Medal,
  mountains: Mountains,
  "mouse-scroll": MouseScroll,
  notebook: Notebook,
  pause: Pause,
  play: Play,
  robot: Robot,
  rocket: Rocket,
  snowflake: Snowflake,
  "speaker-on": SpeakerHigh,
  "speaker-off": SpeakerSlash,
  sparkle: Sparkle,
  stack: Stack,
  target: Target,
  translate: Translate,
  trophy: Trophy,
  users: UsersThree,
  wrench: Wrench,
  x: X,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  weight = "bold",
}: {
  name: IconName;
  className?: string;
  weight?: "regular" | "bold" | "fill" | "duotone";
}) {
  const C = ICONS[name];
  return <C className={className} weight={weight} aria-hidden="true" />;
}
